<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PgOperator.Core\PgOperator.Core.csproj" />
    <ProjectReference Include="..\PgOperator.Infra\PgOperator.Infra.csproj" />
    <ProjectReference Include="..\PgOperator.Diagnostics\PgOperator.Diagnostics.csproj" />
    <ProjectReference Include="..\PgOperator.AI\PgOperator.AI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
